### PR TITLE
Adding size by group

### PR DESCRIPTION
**Pull request by do3cc**

### CODE REVIEW

**Comment by MatthiasLohr** [comment]
Thank you for your Pull Request!

I have two problems found with your code:

First:
```
Traceback (most recent call last):
  File "/etc/munin/plugins/gitlab_group_repo_size", line 50, in <module>
    groups = calc_sizes(registry_root)
  File "/etc/munin/plugins/gitlab_group_repo_size", line 16, in calc_sizes
    for group in os.listdir(os.path.join(startpath, 'repositories')):
OSError: [Errno 13] Permission denied: '/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/repositories'
```

This occurs if i run your plugin without further configuration. Maybe you need some plugin configuration?

Second:
The path ```/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/repositories``` does not exist on every GitLab instance, depending on the usage of docker images. I guess the directories will be created after the first image push. Maybe your script should check that.

**Comment by saily** [comment]
Cool!
I think the required plugin configuration is:
    
    [registry_size]
    user registry

**Comment by do3cc** [comment]
There is already some example config, but I think the wildcard config name doesn't match this new one. So later today I'll check if I simply rename the plugin

**Comment by do3cc** [comment]
@saily you know if we can test these changes without loosing old data?
@MatthiasLohr I took care of both problems but did not test yet.
Since I change another existing plugin I'd like to test first if we can offer a migration of existing data.

**Comment by MatthiasLohr** [comment]
I guess, like https://beeznest.wordpress.com/2011/06/13/howto-rename-munin-node-without-loosing-history/, that's the only way to keep the data.

@saily, what's your opinion about that?

**Comment by saily** [comment]
@MatthiasLohr yes, renaming rrd files should work, but migrating old data is not that important to me.

**Comment by do3cc** [comment]
I feel bad renaming checks, this way deleting history, just for making configuration simpler.
That is why I'd like to try this first on our infra

**Comment by MatthiasLohr** [comment]
@do3cc, anything new?

**Comment by do3cc** [comment]
Not yet, but no worries, we want this in too. We just can't work on this every day, I didn't have time to try the renaming yet.

**Comment by MatthiasLohr** [comment]
@do3cc, anything new about this topic?

**Comment by MatthiasLohr** [comment]
Hey,

i'm going to close this due to inactivity. Feel free to reopen the pull request if you have the time to.

Best regards
Matthias

**Pull request closed without merging**
