### PR TITLE
Add todos by users

### LINKED ISSUE #24: ToDos by users
Measuring pending ToDos by users is important for task management. Let us add ToDos by users.

### PR DESCRIPTION
**Pull request by tnir**
Closes #24

### CODE REVIEW

**Comment by MatthiasLohr** [comment]
Hey,

first, thank you for your pull request, but i have a bunch of remarks on it:

- Have you ever tested your code? There's a closing parenthesis missing in line 26, which leads to a syntax error.
- Even when fixed, there's an error in your SQL query (missing space).
- Even if that is fixed: I'm not convinced that it would be a good idea to have a dynamically growing list of bars in this graph - one bar per users, which could end up in a complete unreadable graph when having >100 active users.
- Even if we decide to add it: Not sure if munin works well if the configuration changes often. As far as i remember, munin calls plugins with the config parameter only on startup. Please take a look into the munin configuration for that how it works with your approach.

My recommendation: Write a whitelabel plugin (e.g. like the ```if_``` plugin), which could be used for each  interface manually. Similarly, you could do this with the users: Write a ```gitlab_todos_by_user_``` plugin, which whould use letters after the last underscore as parameter. E.g.: ```gitlab_todos_by_user_MatthiasLohr```, similar to the ```if_eth0``` plugin.

See also:
```
# ll /etc/munin/plugins/if_*                                                                                                       [9:01:11]
lrwxrwxrwx 1 root root 32 Jul 15  2016 /etc/munin/plugins/if_err_venet0 -> /usr/share/munin/plugins/if_err_
lrwxrwxrwx 1 root root 28 Jul 15  2016 /etc/munin/plugins/if_venet0 -> /usr/share/munin/plugins/if_
```

Best regards
Matthias

**Comment by tnir** [comment]
Thanks for reviewing this. I'm so sorry that I pushed the previous commit rather than the code I'm using in production. I pushed the correct version just now.

- [ ] Have you ever tested your code? There's a closing parenthesis missing in line 26, which leads to a syntax error.
- [ ] Even when fixed, there's an error in your SQL query (missing space).
- [ ] Even if that is fixed: I'm not convinced that it would be a good idea to have a dynamically growing list of bars in this graph - one bar per users, which could end up in a complete unreadable graph when having >100 active users.
- [ ] Even if we decide to add it: Not sure if munin works well if the configuration changes often. As far as i remember, munin calls plugins with the config parameter only on startup. Please take a look into the munin configuration for that how it works with your approach.

**Comment by tnir** [comment]
> I'm not convinced that it would be a good idea to have a dynamically growing list of bars in this graph - one bar per users, which could end up in a complete unreadable graph when having >100 active users.

How about adding cut-off threshold like 10, 20 or 100?

**Comment by MatthiasLohr** [comment]
I think, limiting the number would return in an incomprehensible result. How to order it?

And still: What does the munin documentation say about dynamic configuration changes?

**Comment by tnir** [comment]
@MatthiasLohr Sorting by the number of todos would show top XX todo holders.

Dynamic configuration appears in some official metrics such as [df](https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/df) and docs for it is here: http://guide.munin-monitoring.org/en/latest/plugin/protocol-multigraph.html

**Comment by MatthiasLohr** [comment]
Sorry for the delay.

**Pull request merged**
